# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Image

on:
  push:
    branches: [ python-windows-3.9 ]
  pull_request:
    branches: [ python-windows-3.9 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build
        run: |
          docker build -t geekzsp/python-windows-3.9 .
      - name: Push
        run: |
          docker push geekzsp/python-windows-3.9